In [ ]:
#Задание 1

In [ ]:
# add row 2

In [19]:
import numpy as np
N = int(input('Введите кол-во элементов N: '))
y = - np.sort(- np.arange(N))
#print(y) #Посмотреть результат
#Странное решение, но работает) не нашел как сделать сортировку по убыванию, по этому сделал массив из отрицательных чисел, отсотрировал и убрал минусы

Введите кол-во элементов: 4
[3 2 1 0]
[4 3 2 1 0]


In [ ]:
#Задание 2

In [27]:
N = int(input('Введите кол-во элементов N: '))
mat = np.trace(np.diag(np.full(N +1 , - np.sort(- np.arange(N + 1))))) # Для построения матрицы берется за основу решение задачи 1, но добавляется 1 элемент в матрицу
#print(np.diag(np.full(N +1 , - np.sort(- np.arange(N + 1)))))#Посмотреть матрицу
#print(mat) #Посмотреть результат расчета

Введите кол-во элементов диагональной матрицы: 5
[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]
15


In [ ]:
#Задание 3

In [30]:
from numpy import linalg
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]]) #Левая часть уравнений
b = np.array([4, 12, -3]) #Правая часть уравнений
result = linalg.solve(a, b)
#print(result)#Посмотреть результат расчета

[ 0.46666667  3.84444444 -5.55555556]


In [ ]:
#Задание 4

In [34]:
#Входные данные
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [55]:
def cosine( a, b ): #Честно экспроприировал из лекции
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0
8
0.19999999999999996


In [57]:
i = 0
result = 0
max_match_value = 0
#Думаю, что через while редко кто делает решение.
while i < len(users_stats) :
    if max_match_value < cosine(users_stats[i], next_user_stats):#Проверка является ли косинусное сходство максимально близким
        max_match_value = cosine(users_stats[i], next_user_stats)#Если да - добавляем новое значение для максимально зафиксированного значения косинусного сходства
        result = i + 1 #и проставляем номер(id) пользователя, для которого зафиксировано максимальное сходство (+1 т.к нумерация пользователя логично начинать с 1, а не с 0)
    i += 1
#result - номер(id) самого похожего пользователя
#print(result)#Посмотреть результат расчета


#Решение не универсально т.к. в случае, если подходящих пользователей окажется 2 или больше
#в результат выведется 1 пользователь с минимальным номером(id), а корректно выводить всех.

8
